apiVersion: apps/v1
kind: Deployment
metadata:
  name: ana680-final
  labels:
    app: ana680-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ana680-final
  template:
    metadata:
      labels:
        app: ana680-final
    spec:
      containers:
        - name: ana680-final
          image: cflink987/ana-680-final:1.1
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "5000"
          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: ana680-final-svc
  labels:
    app: ana680-final
spec:
  type: NodePort
  selector:
    app: ana680-final
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30080